# Generated by Django 3.2.4 on 2021-09-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittable',
            options={'verbose_name_plural': 'History Table'},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
