# Generated by Django 3.2.4 on 2021-09-25 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('mobileNumber2', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fatherName', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('mobileNumber', models.CharField(blank=True, max_length=11)),
                ('nidNumber', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('geoLocation', models.JSONField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('connectionFee', models.DecimalField(decimal_places=2, default=1000, max_digits=7)),
                ('connectionAt', models.DateField(blank=True, null=True)),
                ('tv', models.PositiveIntegerField(default=1)),
                ('monthlyCharge', models.DecimalField(decimal_places=2, default=200, max_digits=6)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='catv.area')),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dues', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay')], default='cash', max_length=20)),
                ('accountNumber', models.CharField(blank=True, default='', max_length=11)),
                ('txnId', models.CharField(max_length=200)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catv.customer')),
                ('paidBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('monthlyCharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isPaid', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_bill', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='catv.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='catv.payment')),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_bill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month', 'year', 'customer')},
            },
        ),
    ]
