# Generated by Django 3.2.4 on 2021-09-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='permanentDiscount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='permanentDiscount',
        ),
    ]
