# Generated by Django 3.2.4 on 2021-09-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catv', '0002_auto_20210924_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='preDues',
        ),
    ]
