# Generated by Django 3.2.4 on 2021-09-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catv', '0002_auto_20210926_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bangla_name',
            new_name='banglaName',
        ),
    ]
