# Generated by Django 3.2.4 on 2021-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catv', '0003_rename_bangla_name_company_banglaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banglaName',
            field=models.CharField(max_length=250),
        ),
    ]
